### ISSUE TITLE
[Bancheck] http error 428

### ISSUE THREAD

**Issue by Brandjuh** [PhasecoreX/PCXCogs#16]
While useing the bancheck repport command I get a `http error 428`.

![image](https://user-images.githubusercontent.com/26203955/82424074-f54c4b80-9a84-11ea-81dc-8fcbd0d0f432.png)
![image](https://user-images.githubusercontent.com/26203955/82424083-f8473c00-9a84-11ea-885b-d46b2d86ea86.png)
![image](https://user-images.githubusercontent.com/26203955/82424241-2b89cb00-9a85-11ea-90a5-9ecd1f00040f.png)

**Comment by PhasecoreX** [comment]
I'm not sure what a 428 error is (as it's not listed in the api docs). I have pushed an update for this to hopefully give a bit more descriptive error in the results. Can you please try again?

**Comment by Brandjuh** [comment]
I can't test it as we speak, reported the ban already by hand and it was rejected. So I am not able to do it again. I will let you know if I have a case for it.

**Comment by PhasecoreX** [comment]
I'll leave this open until then!

**Comment by Brandjuh** [comment]
Problem is not solved. 
![image](https://user-images.githubusercontent.com/26203955/83678881-bf5bab00-a5de-11ea-8f1e-8a3127a83202.png)

Also I get a lot of 

```Traceback (most recent call last):
  File "/root/redenv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 83, in wrapped
    ret = await coro(*args, **kwargs)
  File "/root/.local/share/Red-DiscordBot/data/cuffbotv3/cogs/CogManager/cogs/bancheck/bancheck.py", line 189, in bancheckset
    total_bans = await self.config.total_bans()
  File "/root/redenv/lib/python3.8/site-packages/redbot/core/config.py", line 762, in __getattr__
    return getattr(global_group, item)
  File "/root/redenv/lib/python3.8/site-packages/redbot/core/config.py", line 354, in __getattr__
    raise AttributeError("'{}' is not a valid registered Group or value.".format(item))
AttributeError: 'total_bans' is not a valid registered Group or value.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/redenv/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 892, in invoke
    await ctx.command.invoke(ctx)
  File "/root/redenv/lib/python3.8/site-packages/redbot/core/commands/commands.py", line 799, in invoke
    await super().invoke(ctx)
  File "/root/redenv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1230, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/root/redenv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 92, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'total_bans' is not a valid registered Group or value.```

**Comment by PhasecoreX** [comment]
The total_bans thing was caused by a config change, which I have now fixed.
I also think I have fixed the report thing finally, please give it another go.

**Comment by Brandjuh** [comment]
Thanks, tried again and looks like its working fine!
